export const UPDATE_CURRENT_SONG_INDEX = "UPDATE_CURRENT_SONG_INDEX";
export const UPDATE_SONGS = "UPDATE_SONGS";
export const UPDATE_IS_PLAYING = "UPDATE_IS_PLAYING";
export const UPDATE_IS_MENU_OPEN = "UPDATE_IS_MENU_OPEN";