export const UPDATE_CURRENT_SONG_INDEX = "UPDATE_CURRENT_SONG_INDEX";
export const UPDATE_ORIGINAL_SONGS = "UPDATE_ORIGINAL_SONGS";
export const UPDATE_IS_PLAYING = "UPDATE_IS_PLAYING";
export const UPDATE_IS_MENU_OPEN = "UPDATE_IS_MENU_OPEN";
export const UPDATE_FILTERED_SONGS = "UPDATE_FILTERED_SONGS";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const UPDATE_SEARCHED_SONGS = "UPDATE_SEARCHED_SONGS";